environment:
  matrix:
  - nodejs_version: "Stable"
  - nodejs_version: "6"
  - nodejs_version: "5"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off
shallow_clone: true
clone_depth: 1
